name: flutter_nice_toast
description: A beautiful, customizable toast notification package for Flutter with animations and various styles.
version: 0.2.5
homepage: https://github.com/yasinatagun/flutter-nice-toast
repository: https://github.com/yasinatagun/flutter-nice-toast
issue_tracker: https://github.com/yasinatagun/flutter-nice-toast/issues

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

 